### ISSUE TITLE
Recommended way to use ReactJS frontend

### ISSUE THREAD

**Issue by Efrainq07** [neutralinojs/neutralinojs-minimal#1]
Is there a recommended way to run a ReactJS frontend with this template neutralinojs?

I tried the following:

- creating a react project inside the `neutralinojs-minimal` folder. 
- Then adding the `neutralinojs` script to the `index.html` created inside the react project. 
- After that I changed the `url` and `resourcesPath` inside the `neutralino.config.json` file so that they now redirect to the `public` folder of the react project.
- FInally I ran `neu run` on the root of the project.
This only leads to a window opening with a blank page. How can I use ReactJS with this new version of neutralino?

**Comment by GetTuh** [comment]
Try opening HTML file in your browser: you probably have `net::ERR_FILE_NOT_FOUND` errors in your console.
It's necessary to include  `"homepage": "./"` in your package.json file and build the app for production. Alternatively use the boilerplate on my profile.

**Comment by shalithasuranga** [comment]
Thanks, @GetTuh  for answering.  @Efrainq07 you can also check this tutorial: https://youtu.be/4WAur8r7Jhk
