### ISSUE TITLE
Can we include neutralino.js inside package.json instead of it being bundled together in resources/js folder?

### ISSUE THREAD

**Issue by prakhar-pal** [neutralinojs/neutralinojs-minimal#2]
From what I can gather - neutrinalino.js repo houses the original code. Since this is just the fron-tend of starter application, it makes sense to have dependencies inside package.json as package.json is the designated/appropriate place. It will allow implicit imports and make the fron-tend code more obvious.

That'll also allow updating to newer version of neutralinojs easier instead of copy pasting it in the resources folder.

**Comment by zvikasdongre** [comment]
> That'll also allow updating to newer version of neutralinojs easier instead of copy pasting it in the resources folder.

You don't need to copy and paste the `neutralino.js` file, as mentioned (as a comment) in the `index.html`:

>Neutralino.js client. This file is gitignored, 
>     because `neu update` typically downloads it.
>    Avoid copy-pasting it.

**Comment by shalithasuranga** [comment]
Hey.. Thanks for reporting and discussing this issue. Now, you can download the Neutralinojs client from the NPM registry. Please check https://github.com/neutralinojs/neutralino.js for more info. Thanks :tada:
