### ISSUE TITLE
neutralinojs + sveltekit

### ISSUE THREAD

**Issue by ibilux** [neutralinojs/neutralinojs-minimal#6]
Can neutralinojs work with sveltekit ? If yes, can any when provide a template or a starter please ?

**Comment by JVariance** [comment]
Yes, it can, I got it to work.
When I have time, I upload a repository.

**Comment by ibilux** [comment]
@JVariance That's great.
Could you make a template repository for it so wwe can close this issue.

**Comment by JVariance** [comment]
https://github.com/JVariance/SvelteKit-x-Neutralino

**Comment by pathange-s** [comment]
@JVariance great ! Since we have the starter template implemented, we can close this issue ?
cc : @shalithasuranga

**Comment by shalithasuranga** [comment]
Hey.. @pathange-s  yeah sure. thanks for reminding me about this.. Thanks @JVariance for creating a great template :)
